set(EDGE_SOKOL ON)
set(EDGE_SOKOL_GLES3 ON)

set(EDGE_EMSC_COMMON_FLAGS "-sUSE_SDL=2 -sWASM_WORKERS=1 -sSHARED_MEMORY=1 -msimd128 -msse2")
set(EDGE_EMSC_COMPILER_FLAGS "-DEDGE_WEB=1 -DMA_ENABLE_AUDIO_WORKLETS")
set(EDGE_EMSC_LINKER_FLAGS "-sENVIRONMENT=web,worker -sAUDIO_WORKLET=1 -sWASM=1 -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=512Mb -sERROR_ON_UNDEFINED_SYMBOLS=1 -sMIN_WEBGL_VERSION=2 -sMAX_WEBGL_VERSION=2 -sGL_MAX_TEMP_BUFFER_SIZE=16777216 -sLZ4=1 -lidbfs.js -sEXPORT_ES6=1 -sMODULARIZE=1 -sEXPORT_NAME=\"createEdgeModule\"")

# Enable sourcemap support
set(EDGE_EMSC_LINKER_FLAGS "${EDGE_EMSC_LINKER_FLAGS} -gsource-map --source-map-base=/")

# force file system, see: https://github.com/emscripten-core/emscripten/blob/main/tools/file_packager.py
set(EMPACKAGER "${EMSCRIPTEN_ROOT_PATH}/tools/file_packager.py")
set(EDGE_EMSC_LINKER_FLAGS "${EDGE_EMSC_LINKER_FLAGS} -sFORCE_FILESYSTEM=1")

if (CMAKE_BUILD_TYPE STREQUAL "Debug")
  set(EDGE_EMSC_COMPILER_FLAGS "${EDGE_EMSC_COMPILER_FLAGS} -O0")

  # Add -sSAFE_HEAP=1 or -sSAFE_HEAP=2 to test heap and alignment, though slows things down a lot
  set(EDGE_EMSC_LINKER_FLAGS "${EDGE_EMSC_LINKER_FLAGS} -sASSERTIONS=1")
else()
  set(EDGE_EMSC_COMMON_FLAGS "${EDGE_EMSC_COMMON_FLAGS} -flto")
  set(EDGE_EMSC_COMPILER_FLAGS "${EDGE_EMSC_COMPILER_FLAGS} -O3")
  set(EDGE_EMSC_LINKER_FLAGS "${EDGE_EMSC_LINKER_FLAGS} -sASYNCIFY=1")
endif()

add_compile_options("SHELL: ${EDGE_EMSC_COMMON_FLAGS} ${EDGE_EMSC_COMPILER_FLAGS}")
add_link_options("SHELL: ${EDGE_EMSC_COMMON_FLAGS} ${EDGE_EMSC_LINKER_FLAGS}")